using System;
using NCMS;
using NCMS.Utils;
using UnityEngine;
using ReflectionUtility;
using HarmonyLib;
using System.Collections;
using System.Collections.Generic;
using System.Threading;
using life;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static Config;
using System.Reflection;
using UnityEngine.Tilemaps;
using System.IO;
 
namespace Nationalist
{
    class Traits
    {
        //Traits
        public static void init()
        { 

         ActorTrait Mussolinism= new ActorTrait();
         Mussolinism.id = "Mussolinism";
         Mussolinism.path_icon = "ui/Icons/Sr";
         Mussolinism.type = TraitType.Positive;
         Mussolinism.group_id = TraitGroup.Nationalist;
         Mussolinism.can_be_cured = false;
         Mussolinism.needs_to_be_explored = false;
         Mussolinism.can_be_given = true;
         Mussolinism.can_be_removed = true;
         Mussolinism.only_active_on_era_flag = false;
         Mussolinism.era_active_night = false;
         Mussolinism.era_active_moon = false;
         Mussolinism.birth = 9.0f;
         Mussolinism.inherit = 0.0f;
         Mussolinism.base_stats[S.fertility] = 0.0f;
         Mussolinism.base_stats[S.max_children] = 0f;
         Mussolinism.base_stats[S.max_age] = 0f;
         Mussolinism.base_stats[S.attack_speed] = 0;
         Mussolinism.base_stats[S.damage] = 0;
         Mussolinism.base_stats[S.speed] = 0f;
         Mussolinism.base_stats[S.health] = 0;
         Mussolinism.base_stats[S.accuracy] = 0f;
         Mussolinism.base_stats[S.range] = 0;
         Mussolinism.base_stats[S.armor] = 0;
         Mussolinism.base_stats[S.scale] = 0.0f;
         Mussolinism.base_stats[S.dodge] = 0f;
         Mussolinism.base_stats[S.targets] = 0f;
         Mussolinism.base_stats[S.critical_chance] = 0.0f;
         Mussolinism.base_stats[S.knockback] = 0f;
         Mussolinism.base_stats[S.knockback_reduction] = 0f;
         Mussolinism.base_stats[S.intelligence] = -1;
         Mussolinism.base_stats[S.warfare] = 10;
         Mussolinism.base_stats[S.diplomacy] = 1;
         Mussolinism.base_stats[S.stewardship] = -3;
         Mussolinism.base_stats[S.opinion] = 3f;
         Mussolinism.base_stats[S.loyalty_traits] = 3f;
         Mussolinism.base_stats[S.cities] = 7;
         Mussolinism.base_stats[S.zone_range] = 0;
         Mussolinism.action_death = new WorldAction(NoneDeathAction);
         Mussolinism.action_special_effect = new WorldAction(NoneRegularAction);
         Mussolinism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Mussolinism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Mussolinism);
         addTraitToLocalizedLibrary(Mussolinism.id, "Mussolinism ideaology");
         PlayerConfig.unlockTrait("Mussolinism");
         string[] oppositeArrMussolinism = {};
	 Mussolinism.oppositeArr = oppositeArrMussolinism;


         ActorTrait Fascism= new ActorTrait();
         Fascism.id = "Fascism";
         Fascism.path_icon = "ui/Icons/Fr";
         Fascism.type = TraitType.Positive;
         Fascism.group_id = TraitGroup.Nationalist;
         Fascism.can_be_cured = false;
         Fascism.needs_to_be_explored = false;
         Fascism.can_be_given = true;
         Fascism.can_be_removed = true;
         Fascism.only_active_on_era_flag = false;
         Fascism.era_active_night = false;
         Fascism.era_active_moon = false;
         Fascism.birth = 10f;
         Fascism.inherit = 1f;
         Fascism.base_stats[S.fertility] = 0.0f;
         Fascism.base_stats[S.max_children] = 0f;
         Fascism.base_stats[S.max_age] = 0f;
         Fascism.base_stats[S.attack_speed] = 0;
         Fascism.base_stats[S.damage] = 0;
         Fascism.base_stats[S.speed] = 0f;
         Fascism.base_stats[S.health] = 0;
         Fascism.base_stats[S.accuracy] = 0f;
         Fascism.base_stats[S.range] = 0;
         Fascism.base_stats[S.armor] = 0;
         Fascism.base_stats[S.scale] = 0.0f;
         Fascism.base_stats[S.dodge] = 0f;
         Fascism.base_stats[S.targets] = 0f;
         Fascism.base_stats[S.critical_chance] = 0.0f;
         Fascism.base_stats[S.knockback] = 0f;
         Fascism.base_stats[S.knockback_reduction] = 0f;
         Fascism.base_stats[S.intelligence] = 0;
         Fascism.base_stats[S.warfare] = 7;
         Fascism.base_stats[S.diplomacy] = -2;
         Fascism.base_stats[S.stewardship] = 5;
         Fascism.base_stats[S.opinion] = 5;
         Fascism.base_stats[S.loyalty_traits] = 0f;
         Fascism.base_stats[S.cities] = 5;
         Fascism.base_stats[S.zone_range] = 0;
         Fascism.action_death = new WorldAction(NoneDeathAction);
         Fascism.action_special_effect = new WorldAction(NoneRegularAction);
         Fascism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Fascism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Fascism);
         addTraitToLocalizedLibrary(Fascism.id, "Fascism ideology");
         PlayerConfig.unlockTrait("Fascism");
         string[] oppositeArrFascism = { };
	 Fascism.oppositeArr = oppositeArrFascism;


         ActorTrait MonarchFacists= new ActorTrait();
         MonarchFacists.id = "MonarchFacists";
         MonarchFacists.path_icon = "ui/Icons/Kr";
         MonarchFacists.type = TraitType.Positive;
         MonarchFacists.group_id = TraitGroup.Nationalist;
         MonarchFacists.can_be_cured = false;
         MonarchFacists.needs_to_be_explored = false;
         MonarchFacists.can_be_given = true;
         MonarchFacists.can_be_removed = true;
         MonarchFacists.only_active_on_era_flag = false;
         MonarchFacists.era_active_night = false;
         MonarchFacists.era_active_moon = false;
         MonarchFacists.birth = 10f;
         MonarchFacists.inherit = 1f;
         MonarchFacists.base_stats[S.fertility] = 0.0f;
         MonarchFacists.base_stats[S.max_children] = 0f;
         MonarchFacists.base_stats[S.max_age] = 0f;
         MonarchFacists.base_stats[S.attack_speed] = 0;
         MonarchFacists.base_stats[S.damage] = 0;
         MonarchFacists.base_stats[S.speed] = 0f;
         MonarchFacists.base_stats[S.health] = 0;
         MonarchFacists.base_stats[S.accuracy] = 0f;
         MonarchFacists.base_stats[S.range] = 0;
         MonarchFacists.base_stats[S.armor] = 0;
         MonarchFacists.base_stats[S.scale] = 0.0f;
         MonarchFacists.base_stats[S.dodge] = 0f;
         MonarchFacists.base_stats[S.targets] = 0f;
         MonarchFacists.base_stats[S.critical_chance] = 0.0f;
         MonarchFacists.base_stats[S.knockback] = 0f;
         MonarchFacists.base_stats[S.knockback_reduction] = 0f;
         MonarchFacists.base_stats[S.intelligence] = -1;
         MonarchFacists.base_stats[S.warfare] = 1;
         MonarchFacists.base_stats[S.diplomacy] = 1;
         MonarchFacists.base_stats[S.stewardship] = 2;
         MonarchFacists.base_stats[S.opinion] = 0f;
         MonarchFacists.base_stats[S.loyalty_traits] = -1f;
         MonarchFacists.base_stats[S.cities] = 0;
         MonarchFacists.base_stats[S.zone_range] = 1;
         MonarchFacists.action_death = new WorldAction(NoneDeathAction);
         MonarchFacists.action_special_effect = new WorldAction(NoneRegularAction);
         MonarchFacists.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         MonarchFacists.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(MonarchFacists);
         addTraitToLocalizedLibrary(MonarchFacists.id, "MonarchFacists ideology");
         PlayerConfig.unlockTrait("MonarchFacists");
         string[] oppositeArrMonarchFacists = {  };
         MonarchFacists.oppositeArr = oppositeArrMonarchFacists;
 
  
         ActorTrait Corporatism= new ActorTrait();
         Corporatism.id = "Corporatism";
         Corporatism.path_icon = "ui/Icons/Cr";
         Corporatism.type = TraitType.Positive;
         Corporatism.group_id = TraitGroup.Nationalist;
         Corporatism.can_be_cured = false;
         Corporatism.needs_to_be_explored = false;
         Corporatism.can_be_given = true;
         Corporatism.can_be_removed = true;
         Corporatism.only_active_on_era_flag = false;
         Corporatism.era_active_night = false;
         Corporatism.era_active_moon = false;
         Corporatism.birth = 10f;
         Corporatism.inherit = 1f;
         Corporatism.base_stats[S.fertility] = 0.0f;
         Corporatism.base_stats[S.max_children] = -1f;
         Corporatism.base_stats[S.max_age] = 0f;
         Corporatism.base_stats[S.attack_speed] = 0;
         Corporatism.base_stats[S.damage] = 0;
         Corporatism.base_stats[S.speed] = 0f;
         Corporatism.base_stats[S.health] = 0;
         Corporatism.base_stats[S.accuracy] = 0f;
         Corporatism.base_stats[S.range] = 0;
         Corporatism.base_stats[S.armor] = 0;
         Corporatism.base_stats[S.scale] = 0.0f;
         Corporatism.base_stats[S.dodge] = 0f;
         Corporatism.base_stats[S.targets] = 0f;
         Corporatism.base_stats[S.critical_chance] = 0.0f;
         Corporatism.base_stats[S.knockback] = 0f;
         Corporatism.base_stats[S.knockback_reduction] = 0f;
         Corporatism.base_stats[S.intelligence] = 5;
         Corporatism.base_stats[S.warfare] = 3;
         Corporatism.base_stats[S.diplomacy] = 5;
         Corporatism.base_stats[S.stewardship] = 5;
         Corporatism.base_stats[S.opinion] = 5f;
         Corporatism.base_stats[S.loyalty_traits] = 5f;
         Corporatism.base_stats[S.cities] = 1;
         Corporatism.base_stats[S.zone_range] = 0;
         Corporatism.action_death = new WorldAction(NoneDeathAction);
         Corporatism.action_special_effect = new WorldAction(NoneRegularAction);
         Corporatism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Corporatism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Corporatism);
         addTraitToLocalizedLibrary(Corporatism.id, "Corporatism Ideology");
         PlayerConfig.unlockTrait("Corporatism");
         string[] oppositeArrCorporatism = {  };
	 Corporatism.oppositeArr = oppositeArrCorporatism;


         ActorTrait Dictatorship= new ActorTrait();
         Dictatorship.id = "Dictatorship";
         Dictatorship.path_icon = "ui/Icons/Ar";
         Dictatorship.type = TraitType.Positive;
         Dictatorship.group_id = TraitGroup.Nationalist;
         Dictatorship.can_be_cured = false;
         Dictatorship.needs_to_be_explored = false;
         Dictatorship.can_be_given = true;
         Dictatorship.can_be_removed = true;
         Dictatorship.only_active_on_era_flag = false;
         Dictatorship.era_active_night = false;
         Dictatorship.era_active_moon = false;
         Dictatorship.birth = 8f;
         Dictatorship.inherit = 0.0f;
         Dictatorship.base_stats[S.fertility] = -3f;
         Dictatorship.base_stats[S.max_children] = 0f;
         Dictatorship.base_stats[S.max_age] = 0f;
         Dictatorship.base_stats[S.attack_speed] = 0;
         Dictatorship.base_stats[S.damage] = 0;
         Dictatorship.base_stats[S.speed] = 0f;
         Dictatorship.base_stats[S.health] = 0;
         Dictatorship.base_stats[S.accuracy] = 0f;
         Dictatorship.base_stats[S.range] = 0;
         Dictatorship.base_stats[S.armor] = 0;
         Dictatorship.base_stats[S.scale] = 0.0f;
         Dictatorship.base_stats[S.dodge] = 0f;
         Dictatorship.base_stats[S.targets] = 0f;
         Dictatorship.base_stats[S.critical_chance] = 0.0f;
         Dictatorship.base_stats[S.knockback] = 0.0f;
         Dictatorship.base_stats[S.knockback_reduction] = 0.0f;
         Dictatorship.base_stats[S.intelligence] = -3;
         Dictatorship.base_stats[S.warfare] = 7;
         Dictatorship.base_stats[S.diplomacy] = -1;
         Dictatorship.base_stats[S.stewardship] = -3;
         Dictatorship.base_stats[S.opinion] = -1f;
         Dictatorship.base_stats[S.loyalty_traits] = -2f;
         Dictatorship.base_stats[S.cities] = 5;
         Dictatorship.base_stats[S.zone_range] = 2;
         Dictatorship.action_death = new WorldAction(NoneDeathAction);
         Dictatorship.action_special_effect = new WorldAction(NoneRegularAction);
         Dictatorship.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Dictatorship.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Dictatorship);
         addTraitToLocalizedLibrary(Dictatorship.id, "Dictatorship ideaology");
         PlayerConfig.unlockTrait("Dictatorship");
	 string[] oppositeArrDictatorship = {  };
	 Dictatorship.oppositeArr = oppositeArrDictatorship;


	 ActorTrait Kaiser= new ActorTrait();
         Kaiser.id = "Kaiser";
         Kaiser.path_icon = "ui/Icons/Hr";
         Kaiser.type = TraitType.Positive;
         Kaiser.group_id = TraitGroup.Nationalist;
         Kaiser.can_be_cured = false;
         Kaiser.needs_to_be_explored = false;
         Kaiser.can_be_given = true;
         Kaiser.can_be_removed = true;
         Kaiser.only_active_on_era_flag = false;
         Kaiser.era_active_night = false;
         Kaiser.era_active_moon = false;
         Kaiser.birth = 8f;
         Kaiser.inherit = 0.0f;
         Kaiser.base_stats[S.fertility] = -3f;
         Kaiser.base_stats[S.max_children] = 0f;
         Kaiser.base_stats[S.max_age] = 0f;
         Kaiser.base_stats[S.attack_speed] = 0;
         Kaiser.base_stats[S.damage] = 0;
         Kaiser.base_stats[S.speed] = 0f;
         Kaiser.base_stats[S.health] = 0;
         Kaiser.base_stats[S.accuracy] = 0f;
         Kaiser.base_stats[S.range] = 0;
         Kaiser.base_stats[S.armor] = 0;
         Kaiser.base_stats[S.scale] = 0.0f;
         Kaiser.base_stats[S.dodge] = 0f;
         Kaiser.base_stats[S.targets] = 0f;
         Kaiser.base_stats[S.critical_chance] = 0.0f;
         Kaiser.base_stats[S.knockback] = 0.0f;
         Kaiser.base_stats[S.knockback_reduction] = 0.0f;
         Kaiser.base_stats[S.intelligence] = 1;
         Kaiser.base_stats[S.warfare] = 10;
         Kaiser.base_stats[S.diplomacy] = 1;
         Kaiser.base_stats[S.stewardship] = 1;
         Kaiser.base_stats[S.opinion] = 1f;
         Kaiser.base_stats[S.loyalty_traits] = 4f;
         Kaiser.base_stats[S.cities] = 5;
         Kaiser.base_stats[S.zone_range] = 2;
         Kaiser.action_death = new WorldAction(NoneDeathAction);
         Kaiser.action_special_effect = new WorldAction(NoneRegularAction);
         Kaiser.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Kaiser.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Kaiser);
         addTraitToLocalizedLibrary(Kaiser.id, "Kaiser ideaology");
         PlayerConfig.unlockTrait("Kaiser");
	 string[] oppositeArrKaiser = {  };
	 Kaiser.oppositeArr = oppositeArrKaiser;

	
	 ActorTrait Franquist= new ActorTrait();
         Franquist.id = "Franquist";
         Franquist.path_icon = "ui/Icons/Or";
         Franquist.type = TraitType.Positive;
         Franquist.group_id = TraitGroup.Nationalist;
         Franquist.can_be_cured = false;
         Franquist.needs_to_be_explored = false;
         Franquist.can_be_given = true;
         Franquist.can_be_removed = true;
         Franquist.only_active_on_era_flag = false;
         Franquist.era_active_night = false;
         Franquist.era_active_moon = false;
         Franquist.birth = 9.0f;
         Franquist.inherit = 0.0f;
         Franquist.base_stats[S.fertility] = 0.0f;
         Franquist.base_stats[S.max_children] = 5f;
         Franquist.base_stats[S.max_age] = 0f;
         Franquist.base_stats[S.attack_speed] = 0;
         Franquist.base_stats[S.damage] = 0;
         Franquist.base_stats[S.speed] = 0f;
         Franquist.base_stats[S.health] = 0;
         Franquist.base_stats[S.accuracy] = 0f;
         Franquist.base_stats[S.range] = 0;
         Franquist.base_stats[S.armor] = 0;
         Franquist.base_stats[S.scale] = 0.0f;
         Franquist.base_stats[S.dodge] = 0f;
         Franquist.base_stats[S.targets] = 5f;
         Franquist.base_stats[S.critical_chance] = 0.0f;
         Franquist.base_stats[S.knockback] = 0f;
         Franquist.base_stats[S.knockback_reduction] = 0f;
         Franquist.base_stats[S.intelligence] = -1;
         Franquist.base_stats[S.warfare] = 10;
         Franquist.base_stats[S.diplomacy] = 1;
         Franquist.base_stats[S.stewardship] = -3;
         Franquist.base_stats[S.opinion] = -3f;
         Franquist.base_stats[S.loyalty_traits] = 1f;
         Franquist.base_stats[S.cities] = 5;
         Franquist.base_stats[S.zone_range] = 10;
         Franquist.action_death = new WorldAction(NoneDeathAction);
         Franquist.action_special_effect = new WorldAction(NoneRegularAction);
         Franquist.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Franquist.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Franquist);
         addTraitToLocalizedLibrary(Franquist.id, "Franquist ideaology");
         PlayerConfig.unlockTrait("Mussolinism");
         string[] oppositeArrFranquist = {  };
	 Franquist.oppositeArr = oppositeArrFranquist;
        

	 ActorTrait Imperialist= new ActorTrait();
         Imperialist.id = "Imperialist";
         Imperialist.path_icon = "ui/Icons/Ir";
         Imperialist.type = TraitType.Positive;
         Imperialist.group_id = TraitGroup.Nationalist;
         Imperialist.can_be_cured = false;
         Imperialist.needs_to_be_explored = false;
         Imperialist.can_be_given = true;
         Imperialist.can_be_removed = true;
         Imperialist.only_active_on_era_flag = false;
         Imperialist.era_active_night = false;
         Imperialist.era_active_moon = false;
         Imperialist.birth = 9.0f;
         Imperialist.inherit = 0.0f;
         Imperialist.base_stats[S.fertility] = -100.0f;
         Imperialist.base_stats[S.max_children] = -1f;
         Imperialist.base_stats[S.max_age] = 125f;
         Imperialist.base_stats[S.attack_speed] = 0;
         Imperialist.base_stats[S.damage] = 0;
         Imperialist.base_stats[S.speed] = 0f;
         Imperialist.base_stats[S.health] = 0;
         Imperialist.base_stats[S.accuracy] = 0f;
         Imperialist.base_stats[S.range] = 0;
         Imperialist.base_stats[S.armor] = 0;
         Imperialist.base_stats[S.scale] = 0.0f;
         Imperialist.base_stats[S.dodge] = 0f;
         Imperialist.base_stats[S.targets] = 20f;
         Imperialist.base_stats[S.critical_chance] = 0.0f;
         Imperialist.base_stats[S.knockback] = 0f;
         Imperialist.base_stats[S.knockback_reduction] = 0f;
         Imperialist.base_stats[S.intelligence] = 4;
         Imperialist.base_stats[S.warfare] = 50;
         Imperialist.base_stats[S.diplomacy] = 3;
         Imperialist.base_stats[S.stewardship] = 20;
         Imperialist.base_stats[S.opinion] = 10f;
         Imperialist.base_stats[S.loyalty_traits] = 7f;
         Imperialist.base_stats[S.cities] = 15;
         Imperialist.base_stats[S.zone_range] = 50;
         Imperialist.action_death = new WorldAction(NoneDeathAction);
         Imperialist.action_special_effect = new WorldAction(NoneRegularAction);
         Imperialist.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Imperialist.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Imperialist);
         addTraitToLocalizedLibrary(Imperialist.id, "Imperialist ideaology");
         PlayerConfig.unlockTrait("Imperialist");
         string[] oppositeArrImperialist = {  };
	 Imperialist.oppositeArr = oppositeArrImperialist;


	 ActorTrait Theocratic= new ActorTrait();
         Theocratic.id = "Theocratic";
         Theocratic.path_icon = "ui/Icons/Tr";
         Theocratic.type = TraitType.Positive;
         Theocratic.group_id = TraitGroup.Nationalist;
         Theocratic.can_be_cured = false;
         Theocratic.needs_to_be_explored = false;
         Theocratic.can_be_given = true;
         Theocratic.can_be_removed = true;
         Theocratic.only_active_on_era_flag = false;
         Theocratic.era_active_night = false;
         Theocratic.era_active_moon = false;
         Theocratic.birth = 9.0f;
         Theocratic.inherit = 0.0f;
         Theocratic.base_stats[S.fertility] = 0.0f;
         Theocratic.base_stats[S.max_children] = -100f;
         Theocratic.base_stats[S.max_age] = 0f;
         Theocratic.base_stats[S.attack_speed] = 0;
         Theocratic.base_stats[S.damage] = 0;
         Theocratic.base_stats[S.speed] = 0f;
         Theocratic.base_stats[S.health] = 0;
         Theocratic.base_stats[S.accuracy] = 0f;
         Theocratic.base_stats[S.range] = 0;
         Theocratic.base_stats[S.armor] = 0;
         Theocratic.base_stats[S.scale] = 0.0f;
         Theocratic.base_stats[S.dodge] = 0f;
         Theocratic.base_stats[S.targets] = 20f;
         Theocratic.base_stats[S.critical_chance] = 0.0f;
         Theocratic.base_stats[S.knockback] = 0f;
         Theocratic.base_stats[S.knockback_reduction] = 0f;
         Theocratic.base_stats[S.intelligence] = 4;
         Theocratic.base_stats[S.warfare] = -5;
         Theocratic.base_stats[S.diplomacy] = 3;
         Theocratic.base_stats[S.stewardship] = 20;
         Theocratic.base_stats[S.opinion] = 20f;
         Theocratic.base_stats[S.loyalty_traits] = 2f;
         Theocratic.base_stats[S.cities] = 0;
         Theocratic.base_stats[S.zone_range] = 10;
         Theocratic.action_death = new WorldAction(NoneDeathAction);
         Theocratic.action_special_effect = new WorldAction(NoneRegularAction);
         Theocratic.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Theocratic.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Theocratic);
         addTraitToLocalizedLibrary(Theocratic.id, "Theocratic ideaology");
         PlayerConfig.unlockTrait("Theocratic");
         string[] oppositeArrTheocratic = {  };
	 Theocratic.oppositeArr = oppositeArrTheocratic;

	 
	 ActorTrait Syndicalism= new ActorTrait();
         Syndicalism.id = "Syndicalism";
         Syndicalism.path_icon = "ui/Icons/Yr";
         Syndicalism.type = TraitType.Positive;
         Syndicalism.group_id = TraitGroup.Nationalist;
         Syndicalism.can_be_cured = false;
         Syndicalism.needs_to_be_explored = false;
         Syndicalism.can_be_given = true;
         Syndicalism.can_be_removed = true;
         Syndicalism.only_active_on_era_flag = false;
         Syndicalism.era_active_night = false;
         Syndicalism.era_active_moon = false;
         Syndicalism.birth = 9.0f;
         Syndicalism.inherit = 0.0f;
         Syndicalism.base_stats[S.fertility] = 0.0f;
         Syndicalism.base_stats[S.max_children] = 0f;
         Syndicalism.base_stats[S.max_age] = 0f;
         Syndicalism.base_stats[S.attack_speed] = 0;
         Syndicalism.base_stats[S.damage] = 0;
         Syndicalism.base_stats[S.speed] = 0f;
         Syndicalism.base_stats[S.health] = 0;
         Syndicalism.base_stats[S.accuracy] = 0f;
         Syndicalism.base_stats[S.range] = 0;
         Syndicalism.base_stats[S.armor] = 0;
         Syndicalism.base_stats[S.scale] = 0.0f;
         Syndicalism.base_stats[S.dodge] = 0f;
         Syndicalism.base_stats[S.targets] = 0f;
         Syndicalism.base_stats[S.critical_chance] = 0.0f;
         Syndicalism.base_stats[S.knockback] = 0f;
         Syndicalism.base_stats[S.knockback_reduction] = 0f;
         Syndicalism.base_stats[S.intelligence] = 5;
         Syndicalism.base_stats[S.warfare] = 10;
         Syndicalism.base_stats[S.diplomacy] = -10;
         Syndicalism.base_stats[S.stewardship] = 20;
         Syndicalism.base_stats[S.opinion] = -5f;
         Syndicalism.base_stats[S.loyalty_traits] = 10f;
         Syndicalism.base_stats[S.cities] = 2;
         Syndicalism.base_stats[S.zone_range] = 15;
         Syndicalism.action_death = new WorldAction(NoneDeathAction);
         Syndicalism.action_special_effect = new WorldAction(NoneRegularAction);
         Syndicalism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Syndicalism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Syndicalism);
         addTraitToLocalizedLibrary(Syndicalism.id, "Syndicalism ideaology");
         PlayerConfig.unlockTrait("Syndicalism");
         string[] oppositeArrSyndicalism = {  };
	 Syndicalism.oppositeArr = oppositeArrSyndicalism;


	 ActorTrait Falangelist= new ActorTrait();
         Falangelist.id = "Falangelist";
         Falangelist.path_icon = "ui/Icons/Lr";
         Falangelist.type = TraitType.Positive;
         Falangelist.group_id = TraitGroup.Nationalist;
         Falangelist.can_be_cured = false;
         Falangelist.needs_to_be_explored = false;
         Falangelist.can_be_given = true;
         Falangelist.can_be_removed = true;
         Falangelist.only_active_on_era_flag = false;
         Falangelist.era_active_night = false;
         Falangelist.era_active_moon = false;
         Falangelist.birth = 9.0f;
         Falangelist.inherit = 0.0f;
         Falangelist.base_stats[S.fertility] = 0.0f;
         Falangelist.base_stats[S.max_children] = 0f;
         Falangelist.base_stats[S.max_age] = 0f;
         Falangelist.base_stats[S.attack_speed] = 0;
         Falangelist.base_stats[S.damage] = 0;
         Falangelist.base_stats[S.speed] = 0f;
         Falangelist.base_stats[S.health] = 0;
         Falangelist.base_stats[S.accuracy] = 0f;
         Falangelist.base_stats[S.range] = 0;
         Falangelist.base_stats[S.armor] = 0;
         Falangelist.base_stats[S.scale] = 0.0f;
         Falangelist.base_stats[S.dodge] = 0f;
         Falangelist.base_stats[S.targets] = 0f;
         Falangelist.base_stats[S.critical_chance] = 0.0f;
         Falangelist.base_stats[S.knockback] = 0f;
         Falangelist.base_stats[S.knockback_reduction] = 0f;
         Falangelist.base_stats[S.intelligence] = 5;
         Falangelist.base_stats[S.warfare] = 20;
         Falangelist.base_stats[S.diplomacy] = -10;
         Falangelist.base_stats[S.stewardship] = 20;
         Falangelist.base_stats[S.opinion] = 10f;
         Falangelist.base_stats[S.loyalty_traits] = 25f;
         Falangelist.base_stats[S.cities] = 10;
         Falangelist.base_stats[S.zone_range] = 30;
         Falangelist.action_death = new WorldAction(NoneDeathAction);
         Falangelist.action_special_effect = new WorldAction(NoneRegularAction);
         Falangelist.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Falangelist.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Falangelist);
         addTraitToLocalizedLibrary(Falangelist.id, "Falangelist ideaology");
         PlayerConfig.unlockTrait("Falangelist");
         string[] oppositeArrFalangelist = {  };
	 Falangelist.oppositeArr = oppositeArrFalangelist;


 	 ActorTrait Secretism= new ActorTrait();
         Secretism.id = "Secretism";
         Secretism.path_icon = "ui/Icons/Er";
         Secretism.type = TraitType.Positive;
         Secretism.group_id = TraitGroup.Nationalist;
         Secretism.can_be_cured = false;
         Secretism.needs_to_be_explored = false;
         Secretism.can_be_given = true;
         Secretism.can_be_removed = true;
         Secretism.only_active_on_era_flag = false;
         Secretism.era_active_night = false;
         Secretism.era_active_moon = false;
         Secretism.birth = 9.0f;
         Secretism.inherit = 0.0f;
         Secretism.base_stats[S.fertility] = 0.0f;
         Secretism.base_stats[S.max_children] = 0f;
         Secretism.base_stats[S.max_age] = 15f;
         Secretism.base_stats[S.attack_speed] = 0;
         Secretism.base_stats[S.damage] = 0;
         Secretism.base_stats[S.speed] = 0f;
         Secretism.base_stats[S.health] = 0;
         Secretism.base_stats[S.accuracy] = 0f;
         Secretism.base_stats[S.range] = 0;
         Secretism.base_stats[S.armor] = 0;
         Secretism.base_stats[S.scale] = 0.0f;
         Secretism.base_stats[S.dodge] = 0f;
         Secretism.base_stats[S.targets] = 0f;
         Secretism.base_stats[S.critical_chance] = 0.0f;
         Secretism.base_stats[S.knockback] = 0f;
         Secretism.base_stats[S.knockback_reduction] = 0f;
         Secretism.base_stats[S.intelligence] = 15;
         Secretism.base_stats[S.warfare] = 6;
         Secretism.base_stats[S.diplomacy] = -10;
         Secretism.base_stats[S.stewardship] = 20;
         Secretism.base_stats[S.opinion] = -5f;
         Secretism.base_stats[S.loyalty_traits] = -5f;
         Secretism.base_stats[S.cities] = 5;
         Secretism.base_stats[S.zone_range] = 5;
         Secretism.action_death = new WorldAction(NoneDeathAction);
         Secretism.action_special_effect = new WorldAction(NoneRegularAction);
         Secretism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Secretism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Secretism);
         addTraitToLocalizedLibrary(Secretism.id, "Secretism ideaology");
         PlayerConfig.unlockTrait("Secretism");
         string[] oppositeArrSecretism = {  };
	 Secretism.oppositeArr = oppositeArrSecretism;


	 ActorTrait Hitosim= new ActorTrait();
         Hitosim.id = "Hitosim";
         Hitosim.path_icon = "ui/Icons/Mr";
         Hitosim.type = TraitType.Positive;
         Hitosim.group_id = TraitGroup.Nationalist;
         Hitosim.can_be_cured = false;
         Hitosim.needs_to_be_explored = false;
         Hitosim.can_be_given = true;
         Hitosim.can_be_removed = true;
         Hitosim.only_active_on_era_flag = false;
         Hitosim.era_active_night = false;
         Hitosim.era_active_moon = false;
         Hitosim.birth = 9.0f;
         Hitosim.inherit = 0.0f;
         Hitosim.base_stats[S.fertility] = 0.0f;
         Hitosim.base_stats[S.max_children] = 0f;
         Hitosim.base_stats[S.max_age] = 0f;
         Hitosim.base_stats[S.attack_speed] = 0;
         Hitosim.base_stats[S.damage] = 0;
         Hitosim.base_stats[S.speed] = 0f;
         Hitosim.base_stats[S.health] = 0;
         Hitosim.base_stats[S.accuracy] = 0f;
         Hitosim.base_stats[S.range] = 0;
         Hitosim.base_stats[S.armor] = 0;
         Hitosim.base_stats[S.scale] = 0.0f;
         Hitosim.base_stats[S.dodge] = 0f;
         Hitosim.base_stats[S.targets] = 0f;
         Hitosim.base_stats[S.critical_chance] = 0.0f;
         Hitosim.base_stats[S.knockback] = 0f;
         Hitosim.base_stats[S.knockback_reduction] = 0f;
         Hitosim.base_stats[S.intelligence] = -3;
         Hitosim.base_stats[S.warfare] = 15;
         Hitosim.base_stats[S.diplomacy] = -10;
         Hitosim.base_stats[S.stewardship] = 20;
         Hitosim.base_stats[S.opinion] = -5f;
         Hitosim.base_stats[S.loyalty_traits] = 100f;
         Hitosim.base_stats[S.cities] = 0;
         Hitosim.base_stats[S.zone_range] = 30;
         Hitosim.action_death = new WorldAction(NoneDeathAction);
         Hitosim.action_special_effect = new WorldAction(NoneRegularAction);
         Hitosim.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Hitosim.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Hitosim);
         addTraitToLocalizedLibrary(Hitosim.id, "Hitosim ideaology");
         PlayerConfig.unlockTrait("Hitosim");
         string[] oppositeArrHitosim = {  };
	 Hitosim.oppositeArr = oppositeArrHitosim;


	 ActorTrait Carlism= new ActorTrait();
         Carlism.id = "Carlism";
         Carlism.path_icon = "ui/Icons/Pr";
         Carlism.type = TraitType.Positive;
         Carlism.group_id = TraitGroup.Nationalist;
         Carlism.can_be_cured = false;
         Carlism.needs_to_be_explored = false;
         Carlism.can_be_given = true;
         Carlism.can_be_removed = true;
         Carlism.only_active_on_era_flag = false;
         Carlism.era_active_night = false;
         Carlism.era_active_moon = false;
         Carlism.birth = 9.0f;
         Carlism.inherit = 0.0f;
         Carlism.base_stats[S.fertility] = 0.0f;
         Carlism.base_stats[S.max_children] = 0f;
         Carlism.base_stats[S.max_age] = 0f;
         Carlism.base_stats[S.attack_speed] = 0;
         Carlism.base_stats[S.damage] = 0;
         Carlism.base_stats[S.speed] = 0f;
         Carlism.base_stats[S.health] = 0;
         Carlism.base_stats[S.accuracy] = 0f;
         Carlism.base_stats[S.range] = 0;
         Carlism.base_stats[S.armor] = 0;
         Carlism.base_stats[S.scale] = 0.0f;
         Carlism.base_stats[S.dodge] = 0f;
         Carlism.base_stats[S.targets] = 0f;
         Carlism.base_stats[S.critical_chance] = 0.0f;
         Carlism.base_stats[S.knockback] = 0f;
         Carlism.base_stats[S.knockback_reduction] = 0f;
         Carlism.base_stats[S.intelligence] = 3;
         Carlism.base_stats[S.warfare] = 15;
         Carlism.base_stats[S.diplomacy] = 2;
         Carlism.base_stats[S.stewardship] = 3;
         Carlism.base_stats[S.opinion] = -3f;
         Carlism.base_stats[S.loyalty_traits] = 3f;
         Carlism.base_stats[S.cities] = 3;
         Carlism.base_stats[S.zone_range] = 5;
         Carlism.action_death = new WorldAction(NoneDeathAction);
         Carlism.action_special_effect = new WorldAction(NoneRegularAction);
         Carlism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Carlism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Carlism);
         addTraitToLocalizedLibrary(Carlism.id, "Carlism ideaology");
         PlayerConfig.unlockTrait("Carlism");
         string[] oppositeArrCarlism = {  };
	 Carlism.oppositeArr = oppositeArrCarlism;


	 ActorTrait NationalBolchevik= new ActorTrait();
         NationalBolchevik.id = "NationalBolchevik";
         NationalBolchevik.path_icon = "ui/Icons/Br";
         NationalBolchevik.type = TraitType.Positive;
         NationalBolchevik.group_id = TraitGroup.Nationalist;
         NationalBolchevik.can_be_cured = false;
         NationalBolchevik.needs_to_be_explored = false;
         NationalBolchevik.can_be_given = true;
         NationalBolchevik.can_be_removed = true;
         NationalBolchevik.only_active_on_era_flag = false;
         NationalBolchevik.era_active_night = false;
         NationalBolchevik.era_active_moon = false;
         NationalBolchevik.birth = 9.0f;
         NationalBolchevik.inherit = 0.0f;
         NationalBolchevik.base_stats[S.fertility] = 0.0f;
         NationalBolchevik.base_stats[S.max_children] = 0f;
         NationalBolchevik.base_stats[S.max_age] = 0f;
         NationalBolchevik.base_stats[S.attack_speed] = 0;
         NationalBolchevik.base_stats[S.damage] = 0;
         NationalBolchevik.base_stats[S.speed] = 0f;
         NationalBolchevik.base_stats[S.health] = 0;
         NationalBolchevik.base_stats[S.accuracy] = 0f;
         NationalBolchevik.base_stats[S.range] = 0;
         NationalBolchevik.base_stats[S.armor] = 0;
         NationalBolchevik.base_stats[S.scale] = 0.0f;
         NationalBolchevik.base_stats[S.dodge] = 0f;
         NationalBolchevik.base_stats[S.targets] = 0f;
         NationalBolchevik.base_stats[S.critical_chance] = 0.0f;
         NationalBolchevik.base_stats[S.knockback] = 0f;
         NationalBolchevik.base_stats[S.knockback_reduction] = 0f;
         NationalBolchevik.base_stats[S.intelligence] = 3;
         NationalBolchevik.base_stats[S.warfare] = 15;
         NationalBolchevik.base_stats[S.diplomacy] = -3;
         NationalBolchevik.base_stats[S.stewardship] = 25;
         NationalBolchevik.base_stats[S.opinion] = -1f;
         NationalBolchevik.base_stats[S.loyalty_traits] = 5f;
         NationalBolchevik.base_stats[S.cities] = 5;
         NationalBolchevik.base_stats[S.zone_range] = 10;
         NationalBolchevik.action_death = new WorldAction(NoneDeathAction);
         NationalBolchevik.action_special_effect = new WorldAction(NoneRegularAction);
         NationalBolchevik.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         NationalBolchevik.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(NationalBolchevik);
         addTraitToLocalizedLibrary(NationalBolchevik.id, "NationalBolchevik ideaology");
         PlayerConfig.unlockTrait("NationalBolchevik");
         string[] oppositeArrNationalBolchevik = {  };
	 NationalBolchevik.oppositeArr = oppositeArrNationalBolchevik;


	 ActorTrait Expansionism= new ActorTrait();
         Expansionism.id = "Expansionism";
         Expansionism.path_icon = "ui/Icons/Gr";
         Expansionism.type = TraitType.Positive;
         Expansionism.group_id = TraitGroup.Nationalist;
         Expansionism.can_be_cured = false;
         Expansionism.needs_to_be_explored = false;
         Expansionism.can_be_given = true;
         Expansionism.can_be_removed = true;
         Expansionism.only_active_on_era_flag = false;
         Expansionism.era_active_night = false;
         Expansionism.era_active_moon = false;
         Expansionism.birth = 9.0f;
         Expansionism.inherit = 0.0f;
         Expansionism.base_stats[S.fertility] = 0.0f;
         Expansionism.base_stats[S.max_children] = 0f;
         Expansionism.base_stats[S.max_age] = 0f;
         Expansionism.base_stats[S.attack_speed] = 0;
         Expansionism.base_stats[S.damage] = 0;
         Expansionism.base_stats[S.speed] = 0f;
         Expansionism.base_stats[S.health] = 0;
         Expansionism.base_stats[S.accuracy] = 0f;
         Expansionism.base_stats[S.range] = 0;
         Expansionism.base_stats[S.armor] = 0;
         Expansionism.base_stats[S.scale] = 0.0f;
         Expansionism.base_stats[S.dodge] = 0f;
         Expansionism.base_stats[S.targets] = 0f;
         Expansionism.base_stats[S.critical_chance] = 0.0f;
         Expansionism.base_stats[S.knockback] = 0f;
         Expansionism.base_stats[S.knockback_reduction] = 0f;
         Expansionism.base_stats[S.intelligence] = 0;
         Expansionism.base_stats[S.warfare] = 25;
         Expansionism.base_stats[S.diplomacy] = -6;
         Expansionism.base_stats[S.stewardship] = 5;
         Expansionism.base_stats[S.opinion] = 0f;
         Expansionism.base_stats[S.loyalty_traits] = -10f;
         Expansionism.base_stats[S.cities] = 50;
         Expansionism.base_stats[S.zone_range] = 100;
         Expansionism.action_death = new WorldAction(NoneDeathAction);
         Expansionism.action_special_effect = new WorldAction(NoneRegularAction);
         Expansionism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Expansionism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Expansionism);
         addTraitToLocalizedLibrary(Expansionism.id, "Expansionism ideaology");
         PlayerConfig.unlockTrait("Expansionism");
         string[] oppositeArrExpansionism = {  };
	 Expansionism.oppositeArr = oppositeArrExpansionism;


	 ActorTrait EmbraceBepinex= new ActorTrait();
         EmbraceBepinex.id = "EmbraceBepinex";
         EmbraceBepinex.path_icon = "ui/Icons/Jr";
         EmbraceBepinex.type = TraitType.Positive;
         EmbraceBepinex.group_id = TraitGroup.Nationalist;
         EmbraceBepinex.can_be_cured = false;
         EmbraceBepinex.needs_to_be_explored = false;
         EmbraceBepinex.can_be_given = true;
         EmbraceBepinex.can_be_removed = true;
         EmbraceBepinex.only_active_on_era_flag = false;
         EmbraceBepinex.era_active_night = false;
         EmbraceBepinex.era_active_moon = false;
         EmbraceBepinex.birth = 9.0f;
         EmbraceBepinex.inherit = 0.0f;
         EmbraceBepinex.base_stats[S.fertility] = 0.0f;
         EmbraceBepinex.base_stats[S.max_children] = 0f;
         EmbraceBepinex.base_stats[S.max_age] = 0f;
         EmbraceBepinex.base_stats[S.attack_speed] = 0;
         EmbraceBepinex.base_stats[S.damage] = 0;
         EmbraceBepinex.base_stats[S.speed] = 0f;
         EmbraceBepinex.base_stats[S.health] = 0;
         EmbraceBepinex.base_stats[S.accuracy] = 0f;
         EmbraceBepinex.base_stats[S.range] = 0;
         EmbraceBepinex.base_stats[S.armor] = 0;
         EmbraceBepinex.base_stats[S.scale] = 0.0f;
         EmbraceBepinex.base_stats[S.dodge] = 0f;
         EmbraceBepinex.base_stats[S.targets] = 0f;
         EmbraceBepinex.base_stats[S.critical_chance] = 0.0f;
         EmbraceBepinex.base_stats[S.knockback] = 0f;
         EmbraceBepinex.base_stats[S.knockback_reduction] = 0f;
         EmbraceBepinex.base_stats[S.intelligence] = 20;
         EmbraceBepinex.base_stats[S.warfare] = 10;
         EmbraceBepinex.base_stats[S.diplomacy] = 10;
         EmbraceBepinex.base_stats[S.stewardship] = 10;
         EmbraceBepinex.base_stats[S.opinion] = -5f;
         EmbraceBepinex.base_stats[S.loyalty_traits] = 10f;
         EmbraceBepinex.base_stats[S.cities] = 50;
         EmbraceBepinex.base_stats[S.zone_range] = 100;
         EmbraceBepinex.action_death = new WorldAction(NoneDeathAction);
         EmbraceBepinex.action_special_effect = new WorldAction(NoneRegularAction);
         EmbraceBepinex.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         EmbraceBepinex.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(EmbraceBepinex);
         addTraitToLocalizedLibrary(EmbraceBepinex.id, "Bepinex is the Key to modding");
         PlayerConfig.unlockTrait("EmbraceBepinex");
         string[] oppositeArrEmbraceBepinex = {  };
	 EmbraceBepinex.oppositeArr = oppositeArrMussolinism;


	 ActorTrait Tuxism= new ActorTrait();
         Tuxism.id = "Tuxism";
         Tuxism.path_icon = "ui/Icons/Qr";
         Tuxism.type = TraitType.Positive;
         Tuxism.group_id = TraitGroup.Nationalist;
         Tuxism.can_be_cured = false;
         Tuxism.needs_to_be_explored = false;
         Tuxism.can_be_given = true;
         Tuxism.can_be_removed = true;
         Tuxism.only_active_on_era_flag = false;
         Tuxism.era_active_night = false;
         Tuxism.era_active_moon = false;
         Tuxism.birth = 9.0f;
         Tuxism.inherit = 0.0f;
         Tuxism.base_stats[S.fertility] = 0.0f;
         Tuxism.base_stats[S.max_children] = 0f;
         Tuxism.base_stats[S.max_age] = 25f;
         Tuxism.base_stats[S.attack_speed] = 0;
         Tuxism.base_stats[S.damage] = 0;
         Tuxism.base_stats[S.speed] = 0f;
         Tuxism.base_stats[S.health] = 0;
         Tuxism.base_stats[S.accuracy] = 0f;
         Tuxism.base_stats[S.range] = 0;
         Tuxism.base_stats[S.armor] = 0;
         Tuxism.base_stats[S.scale] = 0.0f;
         Tuxism.base_stats[S.dodge] = 0f;
         Tuxism.base_stats[S.targets] = 0f;
         Tuxism.base_stats[S.critical_chance] = 0.0f;
         Tuxism.base_stats[S.knockback] = 0f;
         Tuxism.base_stats[S.knockback_reduction] = 0f;
         Tuxism.base_stats[S.intelligence] = 20;
         Tuxism.base_stats[S.warfare] = 10;
         Tuxism.base_stats[S.diplomacy] = -5;
         Tuxism.base_stats[S.stewardship] = 10;
         Tuxism.base_stats[S.opinion] = 20f;
         Tuxism.base_stats[S.loyalty_traits] = 10;
         Tuxism.base_stats[S.cities] = 30;
         Tuxism.base_stats[S.zone_range] = 50;
         Tuxism.action_death = new WorldAction(NoneDeathAction);
         Tuxism.action_special_effect = new WorldAction(NoneRegularAction);
         Tuxism.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Tuxism.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Tuxism);
         addTraitToLocalizedLibrary(Tuxism.id, "Tuxism is the way, The only true way");
         PlayerConfig.unlockTrait("Tuxism");
         string[] oppositeArrTuxism = {  };
	 Tuxism.oppositeArr = oppositeArrTuxism;


	 ActorTrait Smithers= new ActorTrait();
         Smithers.id = "Smithers";
         Smithers.path_icon = "ui/Icons/Rr";
         Smithers.type = TraitType.Positive;
         Smithers.group_id = TraitGroup.Nationalist;
         Smithers.can_be_cured = false;
         Smithers.needs_to_be_explored = false;
         Smithers.can_be_given = true;
         Smithers.can_be_removed = true;
         Smithers.only_active_on_era_flag = false;
         Smithers.era_active_night = false;
         Smithers.era_active_moon = false;
         Smithers.birth = 9.0f;
         Smithers.inherit = 0.0f;
         Smithers.base_stats[S.fertility] = 0.0f;
         Smithers.base_stats[S.max_children] = 0f;
         Smithers.base_stats[S.max_age] = 0f;
         Smithers.base_stats[S.attack_speed] = 0;
         Smithers.base_stats[S.damage] = 10;
         Smithers.base_stats[S.speed] = 0f;
         Smithers.base_stats[S.health] = 0;
         Smithers.base_stats[S.accuracy] = 10;
         Smithers.base_stats[S.range] = 0;
         Smithers.base_stats[S.armor] = 0;
         Smithers.base_stats[S.scale] = 0.0f;
         Smithers.base_stats[S.dodge] = 0f;
         Smithers.base_stats[S.targets] = 0f;
         Smithers.base_stats[S.critical_chance] = 0.0f;
         Smithers.base_stats[S.knockback] = 0f;
         Smithers.base_stats[S.knockback_reduction] = 0f;
         Smithers.base_stats[S.intelligence] = 20;
         Smithers.base_stats[S.warfare] = 50;
         Smithers.base_stats[S.diplomacy] = -15;
         Smithers.base_stats[S.stewardship] = -10;
         Smithers.base_stats[S.opinion] = -10f;
         Smithers.base_stats[S.loyalty_traits] = 10;
         Smithers.base_stats[S.cities] = 5;
         Smithers.base_stats[S.zone_range] = 20;
         Smithers.action_death = new WorldAction(NoneDeathAction);
         Smithers.action_special_effect = new WorldAction(NoneRegularAction);
         Smithers.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Smithers.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Smithers);
         addTraitToLocalizedLibrary(Smithers.id, "Created by Alex of Italy, the Smithers believe in the use of weapons every time");
         PlayerConfig.unlockTrait("Smithers");
         string[] oppositeArrSmithers = {  };
	 Smithers.oppositeArr = oppositeArrSmithers;


	 ActorTrait Actionist= new ActorTrait();
         Actionist.id = "Actionist";
         Actionist.path_icon = "ui/Icons/Ur";
         Actionist.type = TraitType.Positive;
         Actionist.group_id = TraitGroup.Nationalist;
         Actionist.can_be_cured = false;
         Actionist.needs_to_be_explored = false;
         Actionist.can_be_given = true;
         Actionist.can_be_removed = true;
         Actionist.only_active_on_era_flag = false;
         Actionist.era_active_night = false;
         Actionist.era_active_moon = false;
         Actionist.birth = 9.0f;
         Actionist.inherit = 0.0f;
         Actionist.base_stats[S.fertility] = 0.0f;
         Actionist.base_stats[S.max_children] = 0f;
         Actionist.base_stats[S.max_age] = 0f;
         Actionist.base_stats[S.attack_speed] = 0;
         Actionist.base_stats[S.damage] = 15;
         Actionist.base_stats[S.speed] = 0f;
         Actionist.base_stats[S.health] = 0;
         Actionist.base_stats[S.accuracy] = 15;
         Actionist.base_stats[S.range] = 0;
         Actionist.base_stats[S.armor] = 0;
         Actionist.base_stats[S.scale] = 0.0f;
         Actionist.base_stats[S.dodge] = 0f;
         Actionist.base_stats[S.targets] = 0f;
         Actionist.base_stats[S.critical_chance] = 0.0f;
         Actionist.base_stats[S.knockback] = 0f;
         Actionist.base_stats[S.knockback_reduction] = 0f;
         Actionist.base_stats[S.intelligence] = 15;
         Actionist.base_stats[S.warfare] = 30;
         Actionist.base_stats[S.diplomacy] = 5;
         Actionist.base_stats[S.stewardship] = 5;
         Actionist.base_stats[S.opinion] = 5;
         Actionist.base_stats[S.loyalty_traits] = 1;
         Actionist.base_stats[S.cities] = 7;
         Actionist.base_stats[S.zone_range] = 10;
         Actionist.action_death = new WorldAction(NoneDeathAction);
         Actionist.action_special_effect = new WorldAction(NoneRegularAction);
         Actionist.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Actionist.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Actionist);
         addTraitToLocalizedLibrary(Actionist.id, "From the Western fronts this guys get a Rifle and resolve anything");
         PlayerConfig.unlockTrait("Actionist");
         string[] oppositeArrActionist = {  };
	 Actionist.oppositeArr = oppositeArrActionist;


         ActorTrait Ninners= new ActorTrait();
         Ninners.id = "Ninners";
         Ninners.path_icon = "ui/Icons/Dr";
         Ninners.type = TraitType.Positive;
         Ninners.group_id = TraitGroup.Nationalist;
         Ninners.can_be_cured = false;
         Ninners.needs_to_be_explored = false;
         Ninners.can_be_given = true;
         Ninners.can_be_removed = true;
         Ninners.only_active_on_era_flag = false;
         Ninners.era_active_night = false;
         Ninners.era_active_moon = false;
         Ninners.birth = 0.5f;
         Ninners.inherit = 0.0f;
         Ninners.base_stats[S.fertility] = 0.0f;
         Ninners.base_stats[S.max_children] = 0f;
         Ninners.base_stats[S.max_age] = -50f;
         Ninners.base_stats[S.attack_speed] = 0;
         Ninners.base_stats[S.damage] = -100;
         Ninners.base_stats[S.speed] = 0f;
         Ninners.base_stats[S.health] = 0;
         Ninners.base_stats[S.accuracy] = 0f;
         Ninners.base_stats[S.range] = 0;
         Ninners.base_stats[S.armor] = 0;
         Ninners.base_stats[S.scale] = 0.0f;
         Ninners.base_stats[S.dodge] = 0;
         Ninners.base_stats[S.targets] = 0f;
         Ninners.base_stats[S.critical_chance] = 0.0f;
         Ninners.base_stats[S.knockback] = 0f;
         Ninners.base_stats[S.knockback_reduction] = 0f;
         Ninners.base_stats[S.intelligence] = -100000;
         Ninners.base_stats[S.warfare] = -100000;
         Ninners.base_stats[S.diplomacy] = -100000;
         Ninners.base_stats[S.stewardship] = -100000;
         Ninners.base_stats[S.opinion] = -100000;
         Ninners.base_stats[S.loyalty_traits] = -100000;
         Ninners.base_stats[S.cities] = 0;
         Ninners.base_stats[S.zone_range] = 0;
         Ninners.action_death = new WorldAction(NoneDeathAction);
         Ninners.action_special_effect = new WorldAction(NoneRegularAction);
         Ninners.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Ninners.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Ninners);
         addTraitToLocalizedLibrary(Ninners.id, "Dumbs");
         PlayerConfig.unlockTrait("Ninners");
         string[] oppositeArrNinners = { };
	 Ninners.oppositeArr = oppositeArrNinners;


         ActorTrait Temporadical= new ActorTrait();
         Temporadical.id = "Temporadical";
         Temporadical.path_icon = "ui/Icons/Nr";
         Temporadical.type = TraitType.Positive;
         Temporadical.group_id = TraitGroup.Nationalist;
         Temporadical.can_be_cured = false;
         Temporadical.needs_to_be_explored = false;
         Temporadical.can_be_given = true;
         Temporadical.can_be_removed = true;
         Temporadical.only_active_on_era_flag = false;
         Temporadical.era_active_night = false;
         Temporadical.era_active_moon = false;
         Temporadical.birth = 0.5f;
         Temporadical.inherit = 0.0f;
         Temporadical.base_stats[S.fertility] = 0.0f;
         Temporadical.base_stats[S.max_children] = 0f;
         Temporadical.base_stats[S.max_age] = 10f;
         Temporadical.base_stats[S.attack_speed] = 0;
         Temporadical.base_stats[S.damage] = 0;
         Temporadical.base_stats[S.speed] = 0f;
         Temporadical.base_stats[S.health] = 0;
         Temporadical.base_stats[S.accuracy] = 0f;
         Temporadical.base_stats[S.range] = 0;
         Temporadical.base_stats[S.armor] = 0;
         Temporadical.base_stats[S.scale] = 0.0f;
         Temporadical.base_stats[S.dodge] = 0;
         Temporadical.base_stats[S.targets] = 0f;
         Temporadical.base_stats[S.critical_chance] = 0.0f;
         Temporadical.base_stats[S.knockback] = 0f;
         Temporadical.base_stats[S.knockback_reduction] = 0f;
         Temporadical.base_stats[S.intelligence] = 0;
         Temporadical.base_stats[S.warfare] = 0;
         Temporadical.base_stats[S.diplomacy] = 0;
         Temporadical.base_stats[S.stewardship] = 0;
         Temporadical.base_stats[S.opinion] = 0;
         Temporadical.base_stats[S.loyalty_traits] = -10;
         Temporadical.base_stats[S.cities] = 2;
         Temporadical.base_stats[S.zone_range] = 2;
         Temporadical.action_death = new WorldAction(NoneDeathAction);
         Temporadical.action_special_effect = new WorldAction(NoneRegularAction);
         Temporadical.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Temporadical.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Temporadical);
         addTraitToLocalizedLibrary(Temporadical.id, "Temporadical ideaology");
         PlayerConfig.unlockTrait("Temporadical");
         string[] oppositeArrTemporadical = { };
	 Temporadical.oppositeArr = oppositeArrTemporadical;


         ActorTrait Tsar= new ActorTrait();
         Tsar.id = "Tsar";
         Tsar.path_icon = "ui/Icons/Wr";
         Tsar.type = TraitType.Positive;
         Tsar.group_id = TraitGroup.Nationalist;
         Tsar.can_be_cured = false;
         Tsar.needs_to_be_explored = false;
         Tsar.can_be_given = true;
         Tsar.can_be_removed = true;
         Tsar.only_active_on_era_flag = false;
         Tsar.era_active_night = false;
         Tsar.era_active_moon = false;
         Tsar.birth = 0.5f;
         Tsar.inherit = 0.0f;
         Tsar.base_stats[S.fertility] = 0.0f;
         Tsar.base_stats[S.max_children] = 0f;
         Tsar.base_stats[S.max_age] = -10f;
         Tsar.base_stats[S.attack_speed] = 0;
         Tsar.base_stats[S.damage] = 0;
         Tsar.base_stats[S.speed] = 0f;
         Tsar.base_stats[S.health] = 100;
         Tsar.base_stats[S.accuracy] = 0f;
         Tsar.base_stats[S.range] = 0;
         Tsar.base_stats[S.armor] = 0;
         Tsar.base_stats[S.scale] = 0.0f;
         Tsar.base_stats[S.dodge] = 0;
         Tsar.base_stats[S.targets] = 0f;
         Tsar.base_stats[S.critical_chance] = 0.0f;
         Tsar.base_stats[S.knockback] = 0f;
         Tsar.base_stats[S.knockback_reduction] = 0f;
         Tsar.base_stats[S.intelligence] = 100;
         Tsar.base_stats[S.warfare] = 100;
         Tsar.base_stats[S.diplomacy] = -5;
         Tsar.base_stats[S.stewardship] = 0;
         Tsar.base_stats[S.opinion] = -5;
         Tsar.base_stats[S.loyalty_traits] = 0;
         Tsar.base_stats[S.cities] = 5;
         Tsar.base_stats[S.zone_range] = 0;
         Tsar.action_death = new WorldAction(NoneDeathAction);
         Tsar.action_special_effect = new WorldAction(NoneRegularAction);
         Tsar.action_attack_target = new AttackAction(NoneAttackSomeoneAction);
         Tsar.action_get_hit = new GetHitAction(NoneGetAttackedAction);
         AssetManager.traits.add(Tsar);
         addTraitToLocalizedLibrary(Tsar.id, "Tsar ideaology");
         PlayerConfig.unlockTrait("Tsar");
         string[]  oppositeArrTsar= { };
	 Tsar.oppositeArr = oppositeArrTsar;





        }
        public static bool NoneAttackSomeoneAction(BaseSimObject pSelf, BaseSimObject pTarget, WorldTile pTile = null)
        {
 
             return false;
 
        }
        public static bool NoneRegularAction(BaseSimObject pTarget, WorldTile pTile = null)
        {
 
             return false;
 
        }
        public static bool NoneGetAttackedAction(BaseSimObject pSelf, BaseSimObject pAttackedBy = null, WorldTile pTile = null)
        {
 
             return false;
 
        }
        public static bool NoneDeathAction(BaseSimObject pTarget, WorldTile pTile = null)
        {
 
             return false;
        
 
        }
        public static void addTraitToLocalizedLibrary(string id, string description)
        {
        string language = Reflection.GetField(LocalizedTextManager.instance.GetType(), LocalizedTextManager.instance, "language") as string;
        Dictionary<string, string> localizedText = Reflection.GetField(LocalizedTextManager.instance.GetType(), LocalizedTextManager.instance, "localizedText") as Dictionary<string, string>;
        localizedText.Add("trait_" + id, id);
        localizedText.Add("trait_" + id + "_info", description);
        }
    }
}
